### ISSUE TITLE
dist_to_axis missing?

### ISSUE THREAD

**Issue by AnttiCentria** [3DFin/3DFin#66]
Hi, I followed the tutorial you linked and it says that " It also showcases a way to quickly assess visually the results by using the scalar field "dist_to_axis"."

I cannot find the mentioned scalar field, is there something I overlooked?

**Comment by AnttiCentria** [comment]
Hi, CloudCompare context.

**Comment by rjanvier** [comment]
![Capture d'écran 2024-05-13 085413](https://github.com/3DFin/3DFin/assets/1537100/d7ab43d1-9d79-4dfc-bbe3-0eb44ef06f7d)
well, at the end of the run of 3DFin, in the DBTree (the tree on the left on the CC Graphical Interface) you should have a new "folder" with all sub products of a 3DFin run stacked inside. By default the cloud containing the `dist_axis` field is not activated. You have to click on it in order to activate it, it is name according to the cloud you processed with 3DFin. `dist_axis` is the default activated scalar field for this cloud.

**Comment by rjanvier** [comment]
a short complementary note, the tutorial is wrong about the name of the scalar field, it should be `dist_axes` and note `dist_to_axis`

**Comment by AnttiCentria** [comment]
Thank you!
